language: php

php:
  - 5.6
  - 5.5
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_install:
  - composer self-update

install:
  - composer update --prefer-source $PREFER_LOWEST
